### ISSUE TITLE
Wrong url endpoint in reviews.js

### ISSUE THREAD

**Issue by jakubmakielkowski** [DivanteLtd/magento2-rest-client#15]
In **lib/reviews.js** there is an `/products/%s/review` endpoint in getByProductSku function. Other endpoints contain `reviews` word (with "s").
I have tested it with Divante [review api](https://github.com/DivanteLtd/magento2-review-api) and it looks like url is incorrect.

I may be wrong if there is any other/native Magento 2 review API which supports this syntax.
Else if endpoint is incorrect I would like to contribute to fix that.

**Comment by pkarw** [comment]
ok, cool can you please fix it with a Pull Request please?
