### ISSUE TITLE
PageSize hardcoded for order list with count 20

### ISSUE THREAD

**Issue by dimasch** [DivanteLtd/magento2-rest-client#3]
Hi, Piotr @pkarw. How do you think this can be fixed? It option move to FSV level?

https://github.com/DivanteLtd/magento2-rest-client/blob/6e5f17f8bce0ca8bacf9b59ab707594eb9827cb6/lib/customers.js#L23

**Comment by pkarw** [comment]
Please just add the function call argument with the default value :) Thanks, that's for sure need to be fixed!
