### ISSUE TITLE
orderHistory method should not returns orders from all stores

### ISSUE THREAD

**Issue by juho-jaakkola** [DivanteLtd/magento2-rest-client#36]
The target store is not passed into the request, so if someone has made an account to more than one store using the same email address, the response will contains orders from all those stores.

This is probably quite a rare use case (in most cases users have account only in one store), but it happened to one of our clients.

**Comment by juho-jaakkola** [comment]
I will prepare a PR for this.

**Comment by juho-jaakkola** [comment]
It seems I was using an outdated version of the client. The current one is using store specific user id instead of the email address, and therefore the problem does not exist.

**Comment by simonmaass** [comment]
@juho-jaakkola we have the same problem... if u provide the id like it is now the problem can still exist if you have configured magento to use global users... 

Did you create a PR? or started with the fix?

**Comment by simonmaass** [comment]
![image](https://user-images.githubusercontent.com/32599710/132200113-8a9e4cee-6a7a-43b2-8f1a-f5b5948932c1.png)

**Comment by simonmaass** [comment]
would you mind reopening this issue and creating a PR?
