### ISSUE TITLE
After Magento 2.4.4 upgrade, Error : Signature method HMAC-SHA1 is not supported

### ISSUE THREAD

**Issue by zfaty** [DivanteLtd/magento2-rest-client#39]
Can not Login or Create account using the API ,we got this Error "**Signature method HMAC-SHA1 is not supported**"
The Signature method needs to be changed with HMAC-SHA256
file : lib/rest_client.js

**Comment by simonmaass** [comment]
I have the same problem! @Fifciu @bloodf could maybe someone accept the PR from zfaty and pump the version?

**Comment by simonmaass** [comment]
@zfaty using my fork as a workaround at the moment: https://github.com/MEEVO-Healthcare-GmbH/magento2-rest-client

**Comment by Fifciu** [comment]
Solved in #40 by @zfaty
