### ISSUE TITLE
Wrong check - isNumeric(cartId)  in magento2-rest-client/lib/cart.js 

### ISSUE THREAD

**Issue by VitaliyMartyschuk** [DivanteLtd/magento2-rest-client#7]
@pkarw 
Precondition - place order from vue-storefront checkout to magento 
Description:
Issue - cartId parameter could be not only numeric - after https://github.com/DivanteLtd/vue-storefront-api/blob/master/src/platform/magento2/o2m.js#L70 step cartId is string as it replaced with token returned from magento api call (api.cart.create(null, null)) instead of integer value stored in orderData.
 So after this step all api calls will be executed as guest as in /magento2-rest-client/lib/cart.js each method contain check = if (customerToken && isNumeric(cartId)) 
Expected result - remove isNumeric() check  - like  =  if (customerToken && cartId)

**Comment by pkarw** [comment]
This is desired behavior. In this case - please not the logger messages - we’re forcing user to use the guest user cart in “catch” -> the situation when they passed the cart Id but we cannot use it (Magento sometimes returns error when the quote is in wrong state and we’re bypassing this)
